version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ft_transcendence_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence_network

networks:
  ft_transcendence_network:
    driver: bridge

volumes:
  postgres_data:
