# Generated by Django 5.1.3 on 2025-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('playing', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
