# Generated by Django 5.1.3 on 2025-01-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('game_type', models.CharField(choices=[('classic', 'Classic'), ('custom', 'Custom')], max_length=20)),
            ],
        ),
    ]
