# Generated by Django 5.1.3 on 2025-04-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_player2_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
