# Generated by Django 5.1.3 on 2025-04-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
