# Generated by Django 5.1.3 on 2025-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='embeds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
